package com.giapnt.shopping.cart.model;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.order_subject
     *
     * @mbg.generated
     */
    private String orderSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.ship_date
     *
     * @mbg.generated
     */
    private Date shipDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.required_date
     *
     * @mbg.generated
     */
    private Date requiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.freight
     *
     * @mbg.generated
     */
    private Integer freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.sales_tax
     *
     * @mbg.generated
     */
    private Double salesTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.transaction_status
     *
     * @mbg.generated
     */
    private String transactionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.fulfilled
     *
     * @mbg.generated
     */
    private Integer fulfilled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.is_paid
     *
     * @mbg.generated
     */
    private Integer isPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.payment_date
     *
     * @mbg.generated
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.created_timestamp
     *
     * @mbg.generated
     */
    private Date createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.updated_timestamp
     *
     * @mbg.generated
     */
    private Date updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.shipper_id
     *
     * @mbg.generated
     */
    private String shipperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.payment_id
     *
     * @mbg.generated
     */
    private String paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.id
     *
     * @return the value of core_data.orders.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.id
     *
     * @param id the value for core_data.orders.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.order_subject
     *
     * @return the value of core_data.orders.order_subject
     *
     * @mbg.generated
     */
    public String getOrderSubject() {
        return orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.order_subject
     *
     * @param orderSubject the value for core_data.orders.order_subject
     *
     * @mbg.generated
     */
    public void setOrderSubject(String orderSubject) {
        this.orderSubject = orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.order_date
     *
     * @return the value of core_data.orders.order_date
     *
     * @mbg.generated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.order_date
     *
     * @param orderDate the value for core_data.orders.order_date
     *
     * @mbg.generated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.ship_date
     *
     * @return the value of core_data.orders.ship_date
     *
     * @mbg.generated
     */
    public Date getShipDate() {
        return shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.ship_date
     *
     * @param shipDate the value for core_data.orders.ship_date
     *
     * @mbg.generated
     */
    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.required_date
     *
     * @return the value of core_data.orders.required_date
     *
     * @mbg.generated
     */
    public Date getRequiredDate() {
        return requiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.required_date
     *
     * @param requiredDate the value for core_data.orders.required_date
     *
     * @mbg.generated
     */
    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.freight
     *
     * @return the value of core_data.orders.freight
     *
     * @mbg.generated
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.freight
     *
     * @param freight the value for core_data.orders.freight
     *
     * @mbg.generated
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.sales_tax
     *
     * @return the value of core_data.orders.sales_tax
     *
     * @mbg.generated
     */
    public Double getSalesTax() {
        return salesTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.sales_tax
     *
     * @param salesTax the value for core_data.orders.sales_tax
     *
     * @mbg.generated
     */
    public void setSalesTax(Double salesTax) {
        this.salesTax = salesTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.transaction_status
     *
     * @return the value of core_data.orders.transaction_status
     *
     * @mbg.generated
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.transaction_status
     *
     * @param transactionStatus the value for core_data.orders.transaction_status
     *
     * @mbg.generated
     */
    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.error_message
     *
     * @return the value of core_data.orders.error_message
     *
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.error_message
     *
     * @param errorMessage the value for core_data.orders.error_message
     *
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.fulfilled
     *
     * @return the value of core_data.orders.fulfilled
     *
     * @mbg.generated
     */
    public Integer getFulfilled() {
        return fulfilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.fulfilled
     *
     * @param fulfilled the value for core_data.orders.fulfilled
     *
     * @mbg.generated
     */
    public void setFulfilled(Integer fulfilled) {
        this.fulfilled = fulfilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.is_paid
     *
     * @return the value of core_data.orders.is_paid
     *
     * @mbg.generated
     */
    public Integer getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.is_paid
     *
     * @param isPaid the value for core_data.orders.is_paid
     *
     * @mbg.generated
     */
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.payment_date
     *
     * @return the value of core_data.orders.payment_date
     *
     * @mbg.generated
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.payment_date
     *
     * @param paymentDate the value for core_data.orders.payment_date
     *
     * @mbg.generated
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.is_active
     *
     * @return the value of core_data.orders.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.is_active
     *
     * @param isActive the value for core_data.orders.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.created_by
     *
     * @return the value of core_data.orders.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.created_by
     *
     * @param createdBy the value for core_data.orders.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.updated_by
     *
     * @return the value of core_data.orders.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.updated_by
     *
     * @param updatedBy the value for core_data.orders.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.created_timestamp
     *
     * @return the value of core_data.orders.created_timestamp
     *
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.created_timestamp
     *
     * @param createdTimestamp the value for core_data.orders.created_timestamp
     *
     * @mbg.generated
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.updated_timestamp
     *
     * @return the value of core_data.orders.updated_timestamp
     *
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.updated_timestamp
     *
     * @param updatedTimestamp the value for core_data.orders.updated_timestamp
     *
     * @mbg.generated
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.shipper_id
     *
     * @return the value of core_data.orders.shipper_id
     *
     * @mbg.generated
     */
    public String getShipperId() {
        return shipperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.shipper_id
     *
     * @param shipperId the value for core_data.orders.shipper_id
     *
     * @mbg.generated
     */
    public void setShipperId(String shipperId) {
        this.shipperId = shipperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.payment_id
     *
     * @return the value of core_data.orders.payment_id
     *
     * @mbg.generated
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.payment_id
     *
     * @param paymentId the value for core_data.orders.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.orders.user_id
     *
     * @return the value of core_data.orders.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.orders.user_id
     *
     * @param userId the value for core_data.orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}