package mybatis_generator.model;

import java.util.Date;

public class Suppliers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    private String typeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    private Date createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    private Date updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.id
     *
     * @return the value of core_data.suppliers.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.id
     *
     * @param id the value for core_data.suppliers.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.name
     *
     * @return the value of core_data.suppliers.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.name
     *
     * @param name the value for core_data.suppliers.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.code
     *
     * @return the value of core_data.suppliers.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.code
     *
     * @param code the value for core_data.suppliers.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.address
     *
     * @return the value of core_data.suppliers.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.address
     *
     * @param address the value for core_data.suppliers.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.city
     *
     * @return the value of core_data.suppliers.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.city
     *
     * @param city the value for core_data.suppliers.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.country
     *
     * @return the value of core_data.suppliers.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.country
     *
     * @param country the value for core_data.suppliers.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.phone
     *
     * @return the value of core_data.suppliers.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.phone
     *
     * @param phone the value for core_data.suppliers.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.email
     *
     * @return the value of core_data.suppliers.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.email
     *
     * @param email the value for core_data.suppliers.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.url
     *
     * @return the value of core_data.suppliers.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.url
     *
     * @param url the value for core_data.suppliers.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.payment_methods
     *
     * @return the value of core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    public String getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.payment_methods
     *
     * @param paymentMethods the value for core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    public void setPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.type_goods
     *
     * @return the value of core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    public String getTypeGoods() {
        return typeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.type_goods
     *
     * @param typeGoods the value for core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    public void setTypeGoods(String typeGoods) {
        this.typeGoods = typeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.discount_type
     *
     * @return the value of core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.discount_type
     *
     * @param discountType the value for core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.discount_available
     *
     * @return the value of core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    public Integer getDiscountAvailable() {
        return discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.discount_available
     *
     * @param discountAvailable the value for core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    public void setDiscountAvailable(Integer discountAvailable) {
        this.discountAvailable = discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.current_order
     *
     * @return the value of core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    public String getCurrentOrder() {
        return currentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.current_order
     *
     * @param currentOrder the value for core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    public void setCurrentOrder(String currentOrder) {
        this.currentOrder = currentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.notes
     *
     * @return the value of core_data.suppliers.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.notes
     *
     * @param notes the value for core_data.suppliers.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.is_active
     *
     * @return the value of core_data.suppliers.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.is_active
     *
     * @param isActive the value for core_data.suppliers.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.created_by
     *
     * @return the value of core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.created_by
     *
     * @param createdBy the value for core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.updated_by
     *
     * @return the value of core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.updated_by
     *
     * @param updatedBy the value for core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.created_timestamp
     *
     * @return the value of core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.created_timestamp
     *
     * @param createdTimestamp the value for core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.updated_timestamp
     *
     * @return the value of core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.updated_timestamp
     *
     * @param updatedTimestamp the value for core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}