package mybatis_generator.repository;

import java.util.List;
import mybatis_generator.model.Payments;

public interface PaymentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.payments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.payments
     *
     * @mbg.generated
     */
    int insert(Payments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.payments
     *
     * @mbg.generated
     */
    Payments selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.payments
     *
     * @mbg.generated
     */
    List<Payments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.payments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Payments record);
}