package mybatis_generator.repository;

import java.util.List;
import mybatis_generator.model.Shippers;

public interface ShippersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.shippers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.shippers
     *
     * @mbg.generated
     */
    int insert(Shippers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.shippers
     *
     * @mbg.generated
     */
    Shippers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.shippers
     *
     * @mbg.generated
     */
    List<Shippers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.shippers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shippers record);
}