package mybatis_generator.repository;

import java.util.List;
import mybatis_generator.model.Suppliers;

public interface SuppliersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.suppliers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.suppliers
     *
     * @mbg.generated
     */
    int insert(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.suppliers
     *
     * @mbg.generated
     */
    Suppliers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.suppliers
     *
     * @mbg.generated
     */
    List<Suppliers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.suppliers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Suppliers record);
}