package mybatis_generator.repository;

import java.util.List;
import mybatis_generator.model.UsersRoles;

public interface UsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.users_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.users_roles
     *
     * @mbg.generated
     */
    int insert(UsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.users_roles
     *
     * @mbg.generated
     */
    UsersRoles selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.users_roles
     *
     * @mbg.generated
     */
    List<UsersRoles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.users_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UsersRoles record);
}